@startuml

skinparam component {
    backgroundColor<<Product from This Reactor>> #efefff
    borderColor<<Product from This Reactor>> #5555BB
}

package "Clients" {
  [<&person> NativeApp] as nativeapp
  [<&person> WebApp] as angular
  [<&person> JavaFX] as javafx
  [<&person> Smartphone] as smartapp
}

package "Core Servers" {

        [<&briefcase> Restful Services] as restful <<Product from This Reactor>>
        [Identity Manager] as idm
        [Integration Broker] as integration
}

cloud "Identity Managers" {
    [Facebook or Google] as fb
}

database "Databases" {
  [Identity Management Data] as authdata
  [<&box> Application Data] as appdata <<Product from This Reactor>>
}

cloud "Integration Services" {
    [Google Calendar] as google_calendar
    [Facebook Group(s)] as fb_groups
}

[nativeapp] ..> [idm]
[angular] ..> [idm]
[javafx] ..> [idm]
[smartapp] ..> [idm]

[idm] -down-> [authdata] : 1. Authenticate
[idm] <..> [fb] : 2. (Optional) Authenticate using external IDMs
[restful] -down-> [integration] : 4. Send data for update

[integration] <-down-> [google_calendar] : 5a. Synchronization
[integration] <-down-> [fb_groups] : 5b. Publishing

[nativeapp] -> [restful]
[angular] -> [restful]
[javafx] -> [restful]
[smartapp] -> [restful]

[restful] -down-> [appdata] : 3. Get/Update ServiceData
[idm] <.right. [restful] : Authenticated by

@enduml